services:
    camera-events:
        image: ghcr.io/blcoyote/camera-events:latest
        pull_policy: always
        volumes:
            - camera_events_logs:/app/logs/
        networks:
            - datastorage
            - web
        ports:
            - 8008:80
        environment:
            - MAX_WORKERS=1
            - UVICORN_APP_VERSION=0.2.0
            - UVICORN_FRIGATE_BASEURL=$UVICORN_FRIGATE_BASEURL
            - UVICORN_DOCS_URL=$UVICORN_DOCS_URL
            - UVICORN_FIREBASE_CREDENTIALS=$UVICORN_FIREBASE_CREDENTIALS
            - UVICORN_FIREBASE_APIKEY=$UVICORN_FIREBASE_APIKEY
            - UVICORN_AUTHDOMAIN=$UVICORN_AUTHDOMAIN
            - UVICORN_PROJECTID=$UVICORN_PROJECTID
            - UVICORN_STORAGEBUCKET=$UVICORN_STORAGEBUCKET
            - UVICORN_MESSAGESENDERID=$UVICORN_MESSAGESENDERID
            - UVICORN_APPID=$UVICORN_APPID
            - UVICORN_MEASUREMENTID=$UVICORN_MEASUREMENTID
            - UVICORN_MESSAGINGKEY=$UVICORN_MESSAGINGKEY
        labels:
            - traefik.http.routers.cameraevents.rule=Host(`$DNS_NAME`)
            - traefik.http.routers.cameraevents.tls=true
            - traefik.http.routers.cameraevents.tls.certresolver=lets-encrypt
            - traefik.http.services.cameraevents.loadbalancer.server.port=80
networks:
    web:
        name: web
        external: true
    datastorage:
        name: datastorage
        external: true
volumes:
    camera_events_redis:
        name: camera_events_redis
        driver: local
    camera_events_fcmstore:
        name: camera_events_fcmstore
        driver: local
    camera_events_logs:
        name: camera_events_logs
        driver: local